services:
  certbot:
    image: certbot/dns-cloudflare
    volumes:
      - /srv/openagents/letsencrypt/etc:/etc/letsencrypt
      - /srv/openagents/letsencrypt/log:/var/log/letsencrypt
      - /srv/openagents/letsencrypt/lib:/var/lib/letsencrypt
      - /srv/openagents/letsencrypt/cf.ini:/etc/letsencrypt/cf.ini
    command: certonly --dns-cloudflare --dns-cloudflare-credentials /etc/letsencrypt/cf.ini -d ${SSL_DOMAINS} --cert-name openagents  --dns-cloudflare-propagation-seconds 60  --non-interactive --expand --agree-tos -m $SSL_EMAIL


  pool:
    image: ghcr.io/openagentsinc/openagents-pool:master
    restart: always
    networks:
      - openagents-network
    environment:
      - NOSTR_RELAYS=${NOSTR_RELAYS}
      - POOL_GRPC_BINDING_PORT=${POOL_PORT}
      - POOL_NOSTR_SECRET_KEY=${POOL_NOSTR_SECRET_KEY}
      - POOL_GRPC_SERVER_CRT=/etc/letsencrypt/live/openagents/fullchain.pem
      - POOL_GRPC_SERVER_KEY=/etc/letsencrypt/live/openagents/privkey.pem
      - OPENOBSERVE_ENDPOINT=${OPENOBSERVE_ENDPOINT}
      - OPENOBSERVE_ORG=${OPENOBSERVE_ORG}
      - OPENOBSERVE_STREAM=${OPENOBSERVE_STREAM}
      - OPENOBSERVE_USERNAME=${OPENOBSERVE_USERNAME}
      - OPENOBSERVE_PASSWORD=${OPENOBSERVE_PASSWORD}
      - OPENOBSERVE_BATCHSIZE=${OPENOBSERVE_BATCHSIZE}
      - OPENOBSERVE_FLUSH_INTERVAL=${OPENOBSERVE_FLUSH_INTERVAL}
      - OPENOBSERVE_LOG_LEVEL=${OPENOBSERVE_LOG_LEVEL}
      - POOL_EVENTS_WEBHOOK_ENDPOINTS=${POOL_EVENTS_WEBHOOK_ENDPOINTS}
      - POOL_AUTH_SERVICE=json:/auth/auth.json
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - /srv/openagents/pool/blobs:/blobs
      - /srv/openagents/letsencrypt/etc:/etc/letsencrypt
      - /srv/openagents/pool/auth/:/auth
    ports:
      - "5021:5021"
      - "5000:5021"


  openpool:
    image: ghcr.io/openagentsinc/openagents-pool:master
    restart: always
    networks:
      - openagents-open-network
    environment:
      - NOSTR_RELAYS=${OPEN_POOL_NOSTR_RELAYS}
      - POOL_GRPC_BINDING_PORT=${OPEN_POOL_PORT}
      - POOL_NOSTR_SECRET_KEY=${OPEN_POOL_NOSTR_SECRET_KEY}
      - POOL_GRPC_SERVER_CRT=/etc/letsencrypt/live/openagents/fullchain.pem
      - POOL_GRPC_SERVER_KEY=/etc/letsencrypt/live/openagents/privkey.pem
      - OPENOBSERVE_ENDPOINT=${OPEN_POOL_OPENOBSERVE_ENDPOINT}
      - OPENOBSERVE_ORG=${OPEN_POOL_OPENOBSERVE_ORG}
      - OPENOBSERVE_STREAM=${OPEN_POOL_OPENOBSERVE_STREAM}
      - OPENOBSERVE_USERNAME=${OPEN_POOL_OPENOBSERVE_USERNAME}
      - OPENOBSERVE_PASSWORD=${OPEN_POOL_OPENOBSERVE_PASSWORD}
      - OPENOBSERVE_BATCHSIZE=${OPEN_POOL_OPENOBSERVE_BATCHSIZE}
      - OPENOBSERVE_FLUSH_INTERVAL=${OPEN_POOL_OPENOBSERVE_FLUSH_INTERVAL}
      - OPENOBSERVE_LOG_LEVEL=${OPEN_POOL_OPENOBSERVE_LOG_LEVEL}
      - POOL_EVENTS_WEBHOOK_ENDPOINTS=${OPEN_POOL_EVENTS_WEBHOOK_ENDPOINTS}
      - POOL_AUTH_SERVICE=
      - LOG_LEVEL=${OPEN_POOL_LOG_LEVEL}
    volumes:
      - /srv/openagents/poolopen/blobs:/blobs
      - /srv/openagents/letsencrypt/etc:/etc/letsencrypt
    ports:
      - "6021:6021"
      - "6000:6021"




  extism-runtime:
    image: ghcr.io/openagentsinc/openagents-extism-runtime:master
    restart: always
    environment:
      - POOL_ADDRESS=${POOL_ADDRESS}
      - POOL_PORT=${POOL_PORT}
      - POOL_SSL=${POOL_SSL}
      - EXTISM_RUNTIME_SECRETS_PROVIDERS=https://staging.openagents.com/api/v1/plugins/secrets?secret=${EXTISM_RUNTIME_PLUGINS_SECRET}
      - PLUGINS_REPO=https://staging.openagents.com/api/v1/plugins
      - NODE_TOKEN=${EXTISM_RUNTIME_NODE_TOKEN}
      - OPENOBSERVE_ENDPOINT=${OPENOBSERVE_ENDPOINT}
      - OPENOBSERVE_ORG=${OPENOBSERVE_ORG}
      - OPENOBSERVE_STREAM=${OPENOBSERVE_STREAM}
      - OPENOBSERVE_USERNAME=${OPENOBSERVE_USERNAME}
      - OPENOBSERVE_PASSWORD=${OPENOBSERVE_PASSWORD}
      - OPENOBSERVE_BATCHSIZE=${OPENOBSERVE_BATCHSIZE}
      - OPENOBSERVE_FLUSH_INTERVAL=${OPENOBSERVE_FLUSH_INTERVAL}
      - OPENOBSERVE_LOG_LEVEL=${OPENOBSERVE_LOG_LEVEL}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      -  /srv/openagents/extism-runtime/secrets:/secrets
    networks:
      - openagents-network

  search:
    image: ghcr.io/openagentsinc/openagents-search:master
    restart: always
    environment:
      - POOL_ADDRESS=${POOL_ADDRESS}
      - POOL_PORT=${POOL_PORT}
      - POOL_SSL=${POOL_SSL}
      - NODE_TOKEN=${SEARCH_NODE_TOKEN}
      - OPENOBSERVE_ENDPOINT=${OPENOBSERVE_ENDPOINT}
      - OPENOBSERVE_ORG=${OPENOBSERVE_ORG}
      - OPENOBSERVE_STREAM=${OPENOBSERVE_STREAM}
      - OPENOBSERVE_USERNAME=${OPENOBSERVE_USERNAME}
      - OPENOBSERVE_PASSWORD=${OPENOBSERVE_PASSWORD}
      - OPENOBSERVE_BATCHSIZE=${OPENOBSERVE_BATCHSIZE}
      - OPENOBSERVE_FLUSH_INTERVAL=${OPENOBSERVE_FLUSH_INTERVAL}
      - OPENOBSERVE_LOG_LEVEL=${OPENOBSERVE_LOG_LEVEL}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - /srv/openagents/search/cache:/cache
    networks:
      - openagents-network

    
  embeddings:
    image: ghcr.io/openagentsinc/openagents-embeddings:master
    restart: always
    environment:
      - POOL_ADDRESS=${POOL_ADDRESS}
      - POOL_PORT=${POOL_PORT}
      - POOL_SSL=${POOL_SSL}
      - CACHE_PATH=/cache
      - EMBEDDINGS_TRANSFORMERS_DEVICE=${EMBEDDINGS_TRANSFORMERS_DEVICE}
      - EMBEDDINGS_MODEL=${EMBEDDINGS_MODEL}
      - EMBEDDINGS_MAX_TEXT_LENGTH=${EMBEDDINGS_MAX_TEXT_LENGTH}
      - NODE_TOKEN=${EMBEDDINGS_NODE_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENOBSERVE_ENDPOINT=${OPENOBSERVE_ENDPOINT}
      - OPENOBSERVE_ORG=${OPENOBSERVE_ORG}
      - OPENOBSERVE_STREAM=${OPENOBSERVE_STREAM}
      - OPENOBSERVE_USERNAME=${OPENOBSERVE_USERNAME}
      - OPENOBSERVE_PASSWORD=${OPENOBSERVE_PASSWORD}
      - OPENOBSERVE_BATCHSIZE=${OPENOBSERVE_BATCHSIZE}
      - OPENOBSERVE_FLUSH_INTERVAL=${OPENOBSERVE_FLUSH_INTERVAL}
      - OPENOBSERVE_LOG_LEVEL=${OPENOBSERVE_LOG_LEVEL}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - /srv/openagents/embeddings/cache:/cache
    networks:
      - openagents-network

  retrieval:
    image: ghcr.io/openagentsinc/openagents-document-retrieval:master
    restart: always
    environment:
      - POOL_ADDRESS=${POOL_ADDRESS}
      - POOL_PORT=${POOL_PORT}
      - POOL_SSL=${POOL_SSL}
      - NODE_TOKEN=${DOCUMENT_RETRIEVAL_NODE_TOKEN}
      - OPENOBSERVE_ENDPOINT=${OPENOBSERVE_ENDPOINT}
      - OPENOBSERVE_ORG=${OPENOBSERVE_ORG}
      - OPENOBSERVE_STREAM=${OPENOBSERVE_STREAM}
      - OPENOBSERVE_USERNAME=${OPENOBSERVE_USERNAME}
      - OPENOBSERVE_PASSWORD=${OPENOBSERVE_PASSWORD}
      - OPENOBSERVE_BATCHSIZE=${OPENOBSERVE_BATCHSIZE}
      - OPENOBSERVE_FLUSH_INTERVAL=${OPENOBSERVE_FLUSH_INTERVAL}
      - OPENOBSERVE_LOG_LEVEL=${OPENOBSERVE_LOG_LEVEL}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - /srv/openagents/retrieval/cache:/cache
    networks:
      - openagents-network


  tools:
    image: ghcr.io/openagentsinc/openagents-tools:master
    restart: always
    environment:
      - POOL_ADDRESS=${POOL_ADDRESS}
      - POOL_PORT=${POOL_PORT}
      - POOL_SSL=${POOL_SSL}
      - NODE_TOKEN=${TOOLS_NODE_TOKEN}
      - OPENOBSERVE_ENDPOINT=${OPENOBSERVE_ENDPOINT}
      - OPENOBSERVE_ORG=${OPENOBSERVE_ORG}
      - OPENOBSERVE_STREAM=${OPENOBSERVE_STREAM}
      - OPENOBSERVE_USERNAME=${OPENOBSERVE_USERNAME}
      - OPENOBSERVE_PASSWORD=${OPENOBSERVE_PASSWORD}
      - OPENOBSERVE_BATCHSIZE=${OPENOBSERVE_BATCHSIZE}
      - OPENOBSERVE_FLUSH_INTERVAL=${OPENOBSERVE_FLUSH_INTERVAL}
      - OPENOBSERVE_LOG_LEVEL=${OPENOBSERVE_LOG_LEVEL}
      - LOG_LEVEL=${LOG_LEVEL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - /srv/openagents/tools/cache:/cache
    networks:
      - openagents-network

  hookproxy:
    image: ghcr.io/openagentsinc/openagents-webhook-proxy:master
    restart: always
    environment:
      - SERVER_CRT=/etc/letsencrypt/live/openagents/fullchain.pem
      - SERVER_KEY=/etc/letsencrypt/live/openagents/privkey.pem
    volumes:
      - /srv/openagents/letsencrypt/etc:/etc/letsencrypt
    networks:
      - openagents-network
    ports:
      - "3000:3000"
    command: server

  
  open-retrieval:
    image: ghcr.io/openagentsinc/openagents-document-retrieval:master
    restart: always
    environment:
      - POOL_ADDRESS=${POOL_ADDRESS}
      - POOL_PORT=${OPEN_POOL_PORT}
      - POOL_SSL=${POOL_SSL}
      - NODE_TOKEN=${DOCUMENT_RETRIEVAL_NODE_TOKEN}
      - OPENOBSERVE_ENDPOINT=${OPENOBSERVE_ENDPOINT}
      - OPENOBSERVE_ORG=${OPENOBSERVE_ORG}
      - OPENOBSERVE_STREAM=${OPENOBSERVE_STREAM}
      - OPENOBSERVE_USERNAME=${OPENOBSERVE_USERNAME}
      - OPENOBSERVE_PASSWORD=${OPENOBSERVE_PASSWORD}
      - OPENOBSERVE_BATCHSIZE=${OPENOBSERVE_BATCHSIZE}
      - OPENOBSERVE_FLUSH_INTERVAL=${OPENOBSERVE_FLUSH_INTERVAL}
      - OPENOBSERVE_LOG_LEVEL=${OPENOBSERVE_LOG_LEVEL}
      - LOG_LEVEL=${LOG_LEVEL}
      - PRICE_SATS="${DOCUMENT_RETRIEVAL_PRICE_SATS}"
      - NWC="${DOCUMENT_RETRIEVAL_NWC}"
    volumes:
      - /srv/openagents/retrieval/cache:/cache
    networks:
      - openagents-network

networks:
  openagents-network:
    driver: bridge
  openagents-open-network:
    driver: bridge